on:
  push:
    branches:
      - main

name: "Trigger: Push action"
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@1.1.0
      
