on:
  push:
    branches:
      - main

name: "Trigger: Push action"
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.5.0
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@1.1.0
      - run: pip install proselint
      - run: ./test.sh

      
